# Generated by Django 5.2.8 on 2025-11-20 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcement', '0001_initial'),
        ('department', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='department.department'),
        ),
    ]
