# Generated by Django 5.2.8 on 2025-11-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('job_posted', 'Offre postée'), ('candidate_applied', 'Candidature reçue'), ('employee_added', 'Employé ajouté'), ('announcement_posted', 'Annonce publiée'), ('schedule_created', 'Tâche créée'), ('meeting_scheduled', 'Réunion planifiée')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('previous_value', models.IntegerField(blank=True, null=True)),
                ('change_percentage', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrique',
                'verbose_name_plural': 'Métriques',
                'ordering': ['metric_type'],
            },
        ),
    ]
