# Generated by Django 5.2.8 on 2025-11-21 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('welcome', 'Email de bienvenue'), ('password_reset', 'Réinitialisation de mot de passe'), ('password_changed', 'Mot de passe modifié'), ('account_activated', 'Compte activé'), ('account_deactivated', 'Compte désactivé'), ('notification', 'Notification générale'), ('announcement', 'Annonce'), ('ticket_created', 'Ticket créé'), ('ticket_updated', 'Ticket mis à jour'), ('ticket_closed', 'Ticket fermé')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField(help_text="Corps de l'email en HTML")),
                ('body_text', models.TextField(help_text="Corps de l'email en texte brut (fallback)")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Modèle d'email",
                'verbose_name_plural': "Modèles d'email",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('user_registration', "Inscription d'utilisateur"), ('password_reset', 'Réinitialisation de mot de passe'), ('employee_created', 'Employé créé'), ('employee_updated', 'Employé modifié'), ('announcement_published', 'Annonce publiée'), ('ticket_created', 'Ticket de support créé'), ('ticket_updated', 'Ticket de support mis à jour'), ('system_maintenance', 'Maintenance système')], max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_push', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre de notification',
                'verbose_name_plural': 'Paramètres de notifications',
                'ordering': ['notification_type'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Mon Entreprise', max_length=255)),
                ('company_email', models.EmailField(default='contact@entreprise.com', max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('company_address', models.TextField(blank=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('site_name', models.CharField(default='WeHR', max_length=255)),
                ('site_url', models.URLField(blank=True, default='http://localhost:8000')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
                ('password_min_length', models.IntegerField(default=8)),
                ('password_require_uppercase', models.BooleanField(default=True)),
                ('password_require_lowercase', models.BooleanField(default=True)),
                ('password_require_numbers', models.BooleanField(default=True)),
                ('password_require_special', models.BooleanField(default=True)),
                ('session_timeout_minutes', models.IntegerField(default=30)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('lockout_duration_minutes', models.IntegerField(default=15)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_host', models.CharField(blank=True, max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_from', models.EmailField(blank=True, max_length=254)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('enable_sms_notifications', models.BooleanField(default=False)),
                ('enable_push_notifications', models.BooleanField(default=True)),
                ('max_upload_size_mb', models.IntegerField(default=10)),
                ('allowed_file_types', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètre système',
                'verbose_name_plural': 'Paramètres système',
            },
        ),
    ]
